FROM ghcr.io/graalvm/jdk-community:21-ol9 AS builder

RUN microdnf install -y epel-release && \
    microdnf update && \
    microdnf install -y gcc gcc-c++ make git autoconf tar cmake

RUN mkdir -p /opt /tmp/jprof /tmp/nmt /tmp/pmap /diagnostic

WORKDIR /opt
RUN git clone https://github.com/microsoft/mimalloc && \
    cd mimalloc && \
    mkdir -p build && \
    cd build && \
    cmake -DMI_BUILD_TESTS=OFF ../ && \
    make install
RUN git clone --depth 1 https://github.com/axboe/liburing && \
    cd liburing && \
    ./configure && \
    make -C src install prefix=/usr libdir=/usr/lib64 libdevdir=/usr/lib64 DESTDIR=/tmp/liburing

FROM --platform=$TARGETOS/$TARGETARCH container-registry.oracle.com/graalvm/jdk:25-ol9

LABEL maintainer="yunuservices"

RUN microdnf install -y epel-release && \
    microdnf update && \
    microdnf install -y curl ca-certificates openssl git tar sqlite fontconfig tzdata iproute gcc gcc-c++ freetype libstdc++ lsof glibc glibc-locale-source glibc-langpack-en numactl numactl-libs && \
    microdnf clean all && \
    adduser --home-dir /home/container container
RUN microdnf install -y liburing \
    && microdnf clean all
COPY --from=builder /tmp/liburing/usr/lib64/liburing-ffi.so* /usr/lib64/

USER container
ENV USER=container \
    HOME=/home/container

WORKDIR /home/container/

COPY --from=builder /usr/local/lib64/libmimalloc.so /usr/local/lib/libmimalloc.so
COPY scripts/mimalloc.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
