FROM        container-registry.oracle.com/os/oraclelinux:9-slim AS mimalloc-builder

RUN         microdnf update \
            && microdnf install -y git gcc gcc-c++ make cmake \
            && microdnf clean all

WORKDIR     /opt
RUN         git clone https://github.com/microsoft/mimalloc \
            && cd mimalloc \
            && mkdir -p build \
            && cd build \
            && cmake -DMI_BUILD_TESTS=OFF .. \
            && make install

FROM        container-registry.oracle.com/graalvm/jdk:21-ol9

LABEL       author="Softwarenoob" maintainer="admin@softwarenoob.com"
LABEL       org.opencontainers.image.source="https://github.com/Software-Noob/pterodactyl-images"
LABEL       org.opencontainers.image.licenses="MIT"

RUN         microdnf update \
            && microdnf install -y curl ca-certificates openssl git tar sqlite fontconfig tzdata iproute gcc gcc-c++ freetype libstdc++ lsof glibc-locale-source glibc-langpack-en numactl numactl-libs \
            && microdnf clean all \
            && adduser --home-dir /home/container container

ENV         LC_ALL=en_US.UTF-8
ENV         LANG=en_US.UTF-8
ENV         LANGUAGE=en_US.UTF-8

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        --from=mimalloc-builder /usr/local/lib/libmimalloc.so /usr/local/lib/libmimalloc.so
COPY        scripts/mimalloc.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]
